#constant tensors

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.15.0'

In [4]:
#creating tensors with tf.constant()
scalar=tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:

#check the number of dimensions of a tensor(ndim stands for number of dimentions)
scalar.ndim

0

In [6]:
scalar.shape


TensorShape([])

In [7]:
#create a vector
vector=tf.constant([1,1,1,1])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1], dtype=int32)>

In [8]:
vector.shape

TensorShape([4])

In [9]:
vector.ndim

1

In [10]:
#create a matrix (has more than 1 dimension )
matrix=tf.constant([[10,11],[12,13]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [11]:
matrix.shape

TensorShape([2, 2])

In [12]:
matrix.ndim

2

In [13]:
a=[[1,2],[3,4],[5,6]]

In [14]:
#float matrix
float_matrix=tf.constant(a,dtype=tf.float16,shape=(3,2))
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [15]:
t=[

  [[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12]],

  [[13,14,15,16],
    [17,18,19,20],
    [21,22,23,24]]

  ]



In [16]:
#create a tensor
tensor=tf.constant(value=t)
tensor.ndim

3

In [17]:
tensor.shape

TensorShape([2, 3, 4])

#variable tonsors

In [18]:
#creating tensors with tf.variable
tf.Variable

tensorflow.python.ops.variables.Variable

In [19]:
unchangeable_tensor=tf.constant([10,10])
changeable_tensor=tf.Variable([10,10])
unchangeable_tensor,changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [20]:
#changeable_tensor[0]=8

In [21]:
changeable_tensor.assign([5,5])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [22]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [23]:
#unchangeable_tensor.assign([5,5])

#creating random tensors

In [24]:
tf.range(0,11,2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10], dtype=int32)>

In [25]:
tf.random.Algorithm

<enum 'Algorithm'>

In [26]:
tf.random.set_seed(42)

In [27]:
tf.random.set_seed(2)
normal_tensor1=tf.random.normal((2,2),seed=2)
normal_tensor2=tf.random.normal((2,2),seed=2)
normal_tensor1,normal_tensor2,normal_tensor1==normal_tensor2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7857443 , -0.75540656],
        [-0.99537253, -1.9737345 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.8283597 , -0.354393  ],
        [-1.2814683 , -0.97842145]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False]])>)

In [28]:
normal_tensor3=tf.random.Generator.from_seed(0).normal((2,2))
normal_tensor4=tf.random.Generator.from_seed(0).normal((2,2))
normal_tensor3,normal_tensor4,normal_tensor3==normal_tensor4

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.3544159 ,  0.70454913],
        [ 0.03666191,  0.86918795]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.3544159 ,  0.70454913],
        [ 0.03666191,  0.86918795]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [29]:
tf.random.set_seed(2)
normal_tensor1=tf.random.uniform((2,2),seed=2)
normal_tensor2=tf.random.uniform((2,2),seed=2)
normal_tensor1,normal_tensor2,normal_tensor1==normal_tensor2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.5521052 , 0.6281326 ],
        [0.08688259, 0.5743395 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.1765331 , 0.28047132],
        [0.2726041 , 0.6462158 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False]])>)

In [30]:
uniform_tensor1=tf.random.Generator.from_seed(10).uniform((2,2,2),minval=0,maxval=10)
uniform_tensor2=tf.random.Generator.from_seed(10).uniform(shape=(2,2,2),minval=0,maxval=10)
uniform_tensor1,uniform_tensor2,uniform_tensor1==uniform_tensor2

(<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[9.359867  , 6.513264  ],
         [3.1663585 , 0.01115561]],
 
        [[9.212191  , 3.822806  ],
         [7.7246037 , 9.15142   ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[9.359867  , 6.513264  ],
         [3.1663585 , 0.01115561]],
 
        [[9.212191  , 3.822806  ],
         [7.7246037 , 9.15142   ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=bool, numpy=
 array([[[ True,  True],
         [ True,  True]],
 
        [[ True,  True],
         [ True,  True]]])>)

#shuffle the order of elements in tensors

In [31]:
not_shuffled=tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
not_shuffled

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [32]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [33]:
tf.random.set_seed(12)

In [34]:
tf.random.set_seed(2)#global level random seed
tf.random.shuffle(not_shuffled,seed=0)#operation level random seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

#other ways to make tensor

In [35]:
tf.ones((10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
tf.zeros([3,3,3])


<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [37]:
import numpy as np
numpy_array=np.arange(30)
numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
a=tf.constant(numpy_array,shape=(2,3,5))
a

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [39]:
b=tf.constant(numpy_array,)
b

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

In [40]:
a==b

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [41]:
b[:12]

<tf.Tensor: shape=(12,), dtype=int64, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [42]:
b[:,tf.newaxis]

<tf.Tensor: shape=(30, 1), dtype=int64, numpy=
array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])>

In [43]:
a.shape,b.shape

(TensorShape([2, 3, 5]), TensorShape([30]))

In [44]:
a.ndim,b.ndim

(3, 1)

#getting information from tensor

In [45]:

zero_tensor=tf.zeros((2,3,4,5),name='zeros')
zero_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
zero_tensor.shape

TensorShape([2, 3, 4, 5])

In [47]:
tf.size( zero_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [48]:
len(zero_tensor)

2

In [49]:
tf.size(zero_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [50]:
zero_tensor.ndim

4

In [51]:
zero_tensor.ref()

<Reference wrapping <tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>>

In [52]:
zero_tensor.dtype

tf.float32

In [53]:
zero_tensor.get_shape()

TensorShape([2, 3, 4, 5])

In [54]:
zero_tensor.backing_device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [55]:
zero_tensor.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [56]:
tf.identity(zero_tensor)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [57]:
zero_tensor.dtype

tf.float32

In [58]:
tf.size(zero_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [59]:
tf.size(zero_tensor).numpy()

120

#indexing

In [60]:
zero_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [61]:
zero_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [62]:
zero_tensor.shape

TensorShape([2, 3, 4, 5])

In [63]:
tf.reshape(zero_tensor,[2,3,5,4])

<tf.Tensor: shape=(2, 3, 5, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [64]:
zero_tensor[-1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [65]:
zero_tensor[:,-1,-1,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [66]:
zero_tensor[...]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [67]:
rank_2_tensor=tf.random.shuffle(tf.random.normal((2,2)))
rank_2_tensor[...,None]

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 1.3789066 ],
        [-1.0405852 ]],

       [[ 0.43616885],
        [-1.9093795 ]]], dtype=float32)>

In [68]:
rank_2_tensor.shape

TensorShape([2, 2])

In [69]:
tf.expand_dims(rank_2_tensor,0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[ 1.3789066 , -1.0405852 ],
        [ 0.43616885, -1.9093795 ]]], dtype=float32)>

In [70]:
tf.expand_dims(rank_2_tensor,1)

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[ 1.3789066 , -1.0405852 ]],

       [[ 0.43616885, -1.9093795 ]]], dtype=float32)>

In [71]:
tf.expand_dims(rank_2_tensor,2)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 1.3789066 ],
        [-1.0405852 ]],

       [[ 0.43616885],
        [-1.9093795 ]]], dtype=float32)>

In [72]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.3789066 , -1.0405852 ],
       [ 0.43616885, -1.9093795 ]], dtype=float32)>

#manipilating tensors (tensor operations)

**basic operations**   +  -  *  /



In [73]:
import tensorflow as tf


In [74]:
tensor=tf.constant([[1,2],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [75]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [76]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [77]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [78]:
  tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [79]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [80]:
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

#matrix multiplication


In [81]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [82]:
import numpy as np
np.dot(tensor,tensor)

array([[ 7, 10],
       [15, 22]], dtype=int32)

In [83]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [84]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [85]:
x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.constant([[7,8],[9,10],[11,12]])

In [86]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [87]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))#outer dimension is [3,3]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [88]:
x.shape,tf.reshape(y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [89]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)#outer dimension is [2,2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [90]:
tf.reshape(x,shape=(2,3)).shape,y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [91]:
tf.expand_dims(x,axis=2)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [92]:
x,tf.reshape(x,(2,3)),tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [93]:
tf.reshape(x,(2,3))@y, tf.matmul(tf.reshape(x,(2,3)),y),  tf.matmul(tf.transpose(x),y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

In [94]:
tf.tensordot(tf.reshape(x,(2,3)),y,axes=1), tf.tensordot(tf.transpose(x),y,axes=1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

#changing the data type of a tensor


In [95]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [96]:
tf.__version__

'2.15.0'

In [100]:
#default data type
tf.constant(10).dtype

tf.int32

In [101]:
tf.constant(10.0).dtype

tf.float32

In [105]:
tf.constant(10.45455646546546555545646565566).dtype

tf.float32

In [107]:
tf.constant('c').dtype

tf.string

In [108]:
#change default data type
tf.constant(10.0,dtype=tf.float16).dtype

tf.float16

In [113]:
tf.cast(tf.constant(10.5554654),dtype=tf.int8).dtype

tf.int8

# Aggreagating tensors



In [115]:
c=tf.constant([-7,-10])
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [117]:
#get absolute values
tf.abs(c)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [120]:
tf.minimum(c,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [121]:
tf.maximum(c,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [141]:
np.random.randint(0,100,size=50,)#discrete

array([ 3,  9, 74, 48,  3, 73, 71, 86, 11, 40, 46, 12, 34, 49, 75, 50, 61,
       64, 41, 91,  4, 89, 49, 44, 55,  4,  4, 40, 79, 99, 14, 12, 84, 97,
       35, 67, 46, 15,  1, 98, 86, 15, 45, 99, 90, 51, 79, 39, 54, 49])

In [128]:
np.random.uniform(0,100,size=50)#continuous

array([58.01765053,  8.9472264 , 55.13310905, 51.99023441, 56.99560265,
       19.85571876, 73.68278157, 70.73676982, 42.90603921, 91.15143936,
       67.97138949, 17.82417386, 19.50963846, 67.23441037, 27.63360291,
        7.85679413, 65.95512647, 95.30561316, 96.560244  , 50.62893839,
       61.00997345,  1.37584263, 62.9604604 , 65.52876911, 45.91307038,
       13.94547081, 38.85526445,  3.19956267, 70.50251151, 90.67002444,
       69.53206812, 41.53926907, 54.20535291, 87.82021785, 19.73336538,
        2.91855738, 15.17657021, 98.07406475, 89.19478431, 64.01882536,
       35.94001735, 54.90771483, 44.0349746 , 64.41866861, 30.47041596,
       24.16125648, 80.00101525, 18.65667304, 68.99128906,  4.78389408])

In [137]:
tf.random.uniform(shape=(50,),minval=0,maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([52, 61, 52,  3, 14, 29, 54, 13, 30, 85,  0, 23, 49, 73, 10, 74, 11,
       72, 90, 71, 66, 68, 45, 22, 47,  5, 92, 85, 55, 59, 83, 37, 49, 16,
       32, 87, 58, 33, 33, 33,  1,  0, 45, 54, 93, 37, 81, 19, 95, 61],
      dtype=int32)>

In [138]:
tf.random.uniform(shape=(50,),minval=0,maxval=100,dtype=tf.float32)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([98.38634  ,  7.9129934, 84.21965  , 37.040222 , 82.353615 ,
       59.884716 , 79.03932  , 33.400238 ,  3.556645 , 97.36173  ,
       46.22346  , 50.765823 ,  6.254959 , 97.96231  , 22.980988 ,
       51.605343 , 53.278625 , 65.80595  , 86.49108  ,  6.701267 ,
        6.141019 , 58.24499  , 21.437847 ,  6.1653852, 81.46051  ,
       77.164116 , 84.01798  , 93.37169  ,  5.5607915, 44.556522 ,
       39.474464 , 87.095856 , 15.693879 , 24.366724 , 74.985886 ,
       98.42122  , 21.434414 ,  0.6312609, 37.179863 , 93.87218  ,
       92.965195 , 86.47525  , 29.967094 , 47.21509  , 49.0059   ,
       59.92687  , 42.192173 , 39.248146 , 43.211617 , 67.28795  ],
      dtype=float32)>

In [143]:
d=tf.constant(tf.random.shuffle(tf.random.uniform(shape=(50,),minval=0,maxval=100,dtype=tf.int32)))
d

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([87, 33, 97, 59, 86, 75, 13, 59, 97, 63, 44, 56, 27,  6, 90,  2, 10,
       18, 39,  5, 61, 56, 42, 40, 73,  2, 44, 21, 81, 54,  6, 34, 17, 59,
       92, 49, 39, 99, 71, 71,  4, 74, 78, 53, 16, 25, 98, 75, 24, 24],
      dtype=int32)>

In [145]:
d.shape, d.ndim, tf.size(d)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [148]:
#finding the minimum
np.min( d), tf.reduce_min(d)

(2, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [149]:
#maximum
np.max(d), tf.reduce_max(d)

(99, <tf.Tensor: shape=(), dtype=int32, numpy=99>)

In [150]:
#mean
np.mean(d), tf.reduce_mean(d)

(48.96, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [151]:
#sum
tf.reduce_sum(d)

<tf.Tensor: shape=(), dtype=int32, numpy=2448>

In [152]:
#production
tf.reduce_prod(d)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [160]:
#std
tf.math.reduce_std(tf.cast(d,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.644533>

In [155]:
#variance
tf.math.reduce_variance(tf.cast(d,dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=878.79834>

In [157]:
d.dtype

tf.int32

In [161]:
import tensorflow_probability as tfp

In [167]:
#variance
tfp.stats.variance(d)

<tf.Tensor: shape=(), dtype=int32, numpy=879>

In [168]:
#std
tfp.stats.stddev(tf.cast(d,dtype  =tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.644533>

#finding the positional maximum and minimum

In [179]:
e=tf.random.uniform(shape=(50,),minval=0,maxval=100,dtype=tf.float32)
e

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([31.31193  , 56.870197 , 40.43113  , 78.92606  , 59.05484  ,
       13.684058 , 32.654045 , 20.851303 , 96.84834  , 25.871288 ,
       56.644035 , 71.07832  , 20.27322  , 84.879135 , 51.229607 ,
       17.55066  , 85.00515  ,  7.406366 , 72.81871  , 79.00918  ,
       32.609283 , 90.61964  , 57.306206 , 56.851387 , 75.01179  ,
       61.03474  , 34.90281  , 45.715405 , 69.60535  , 92.22743  ,
       99.73568  , 48.15869  , 80.82029  ,  1.7959356, 19.548702 ,
       29.504753 , 32.6048   , 69.285416 , 85.27893  ,  8.893478 ,
       84.99932  , 92.87277  , 85.8469   , 36.78087  ,  1.1004329,
       85.973015 , 41.098606 , 35.351036 , 77.6158   , 21.202003 ],
      dtype=float32)>

In [176]:
e.dtype

tf.float32

In [181]:
#maximum posotion
np.argmax(e),tf.argmax(e)

(30, <tf.Tensor: shape=(), dtype=int64, numpy=30>)

In [182]:
e[30]

<tf.Tensor: shape=(), dtype=float32, numpy=99.73568>

In [183]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=float32, numpy=99.73568>

In [188]:
#chaek for equality
assert e[tf.argmax(e)]==tf.reduce_max(e)

In [189]:
#minimum position
tf.argmin(e)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [190]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1004329>

In [191]:
e[tf.argmin(e)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.1004329>

#Squezzing a tensor (removing all single dimensions)

In [215]:
tf.random.set_seed(42)
f=tf.random.uniform(shape=(1,1,1,1,50))
f

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [211]:
f.shape, f.ndim, tf.size(f), len(f)

(TensorShape([1, 1, 1, 1, 50]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 1)

In [216]:
g_squeezed=tf.squeeze(f)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [217]:
g_squeezed.shape, g_squeezed.ndim, tf.size(g_squeezed), len(g_squeezed)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, 50)

#One_hot encoding tensors

In [226]:
color_list=[0,1,2,3]#red,gren,blue,purple
tf.one_hot(color_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [229]:
tf.one_hot(color_list,depth=4,on_value=True,off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

In [8]:

h=tf.range(1,11)
h

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [6]:
tf.argmax(h)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [7]:
tf.reduce_max(h)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [10]:
#square
tf.square(h)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)>

In [13]:
#square root
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777], dtype=float32)>

In [14]:
#log
tf.math.log(tf.cast(h,dtype=tf.float32))


<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851], dtype=float32)>

In [15]:
tf.math.reduce_sum(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=55.0>

In [16]:
tf.math.add(h,10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int32)>

In [17]:
tf.math.subtract(h,10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0], dtype=int32)>

In [18]:
tf.math.multiply(h,10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int32)>

In [19]:
tf.math.divide(h,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])>

#Tensors and Numpy

In [24]:
#convert numpy to tensor
j=tf.Variable(np.array([1,2,3,4,5]))
j, j.dtype, type(j)

(<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([1, 2, 3, 4, 5])>,
 tf.int64,
 tensorflow.python.ops.resource_variable_ops.ResourceVariable)

In [32]:
#convert tensor to numpy
np.array(j), np.array(j).dtype, type(np.array(j))

(array([1, 2, 3, 4, 5]), dtype('int64'), numpy.ndarray)

In [33]:
#convert tensor to numpy
j.numpy(), j.numpy().dtype, type(j.numpy())

(array([1, 2, 3, 4, 5]), dtype('int64'), numpy.ndarray)

In [39]:
numpy_array=tf.constant(np.array([1,2,3,4,5]))
tensor_array=tf.constant([1,2,3,4,5])
(numpy_array.dtype), (tensor_array.dtype)

(tf.int64, tf.int32)

#Finding access to GPUs

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [4]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [1]:
!nvidia-smi

Wed Jul 31 17:15:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--